---
- name: install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
      - libapache2-mod-php5
      
- name: apache php config
  template: src=apache/php.conf dest=/etc/apache2/sites-available/php.conf
  notify: reload apache
  tags:
      - config

- name: apache ports config
  template: src=apache/ports.conf dest=/etc/apache2/ports.conf
  notify: restart apache
  tags:
      - config

- name: Remove 000-default
  file: dest=/etc/apache2/sites-enabled/000-default.conf
        state=absent
  when: php_apache_remove_default_conf
  notify: reload apache
  
- name: enable apache php config
  file: state=link src=../sites-available/php.conf dest=/etc/apache2/sites-enabled/php.conf
  notify: reload apache
  when: php_apache_no_conf == False
  tags:
      - config

- name: ensure role conf is disabled
  file: dest=/etc/apache2/sites-enabled/php.conf state=absent
  when: php_apache_no_conf
