---
- name: install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
      - libapache2-mod-php5
      
      
- name: nginx php config
  template: src=apache/php.conf dest=/etc/apache2/sites-available/php.conf
  notify: reload apache
  tags:
      - config

- name: Remove 000-default
  file: dest=/etc/apache2/sites-enabled/000-default
        state=absent
  when: php_apache_remove_default_conf == True
  notify: reload apache
  
- name: enable nginx rd config
  file: state=link src=../sites-available/php.conf dest=/etc/apache2/sites-enabled/php.conf
  notify: reload apache
  tags:
      - config
